### ISSUE TITLE
CPX opcode being written into disassembled files as CPY

### ISSUE THREAD

**Issue by AleffCorrea** [BlockoS/Etripator#57]
In all instances where a CPX would have been, the program writes CPY. This is specially obvious when looking at loops that use X as a counter but evaluate Y instead.

**Comment by BlockoS** [comment]
Thanks! Copy/paste are evil :'(
The fix is to replace "cpy " by "cpx " in opcodes.c at lines 272, 276 and 284.

**Comment by AleffCorrea** [comment]
All good now, thanks!
