### ISSUE TITLE
Feature request:  comment support.

### ISSUE THREAD

**Issue by konkers** [BlockoS/Etripator#66]
Etripator is a great tool, thanks!

I find myself commenting the disassembly as I go along.  These comments get wiped by future runs of etripator.  It would be great to have some sort of "merge" support that took the comment from an older disassembly.

**Comment by BlockoS** [comment]
Cool! Glad it helps.

I found myself in a similar situation. Unfortunately I didn't find any good solution (either inside etripator or using scripts).

My workflow is: I have 2 files. One is the output of etripator and the other is the commented version. 
After running etripator, I'm using a tool like Meld or Araxis Merge to manually merge them.
It's a little bit tedious but at least I have a total control of the merge process.
